# Generated by Django 5.1.1 on 2024-10-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
