# Generated by Django 5.1.1 on 2024-10-04 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_interest_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
